(function($){'use strict';function video_responsive(){jQuery('iframe[src*="youtube.com"]').wrap('<div class="embed-responsive embed-responsive-16by9"></div>');jQuery('iframe[src*="vimeo.com"]').wrap('<div class="embed-responsive embed-responsive-16by9"></div>')}
function lightbox_popup(){lc_lightbox('.elem',{wrap_class:'lcl_fade_oc',gallery:!0,thumb_attr:'data-lcl-thumb',skin:'minimal',radius:0,padding:0,border_w:0,})}
function magnific_video(){jQuery('.mfp-video').magnificPopup({type:'iframe',})}
function popup_vertical_center(){jQuery(function(){function reposition(){var modal=jQuery(this),dialog=modal.find('.modal-dialog');modal.css('display','block');dialog.css("margin-top",Math.max(0,(jQuery(window).height()-dialog.height())/2))}
jQuery('.modal').on('show.bs.modal',reposition);jQuery(window).on('resize',function(){jQuery('.modal:visible').each(reposition)})})}
function sticky_header(){if(jQuery('.sticky-header').length){var sticky=new Waypoint.Sticky({element:jQuery('.sticky-header')})}}
function sticky_sidebar(){$('.rightSidebar').theiaStickySidebar({additionalMarginTop:100})}
function menu_navigation(){jQuery(".menu-btn").on('click',function(){jQuery(".full-menu").fadeIn(500)});jQuery('.full-menu-close').on('click',function(){jQuery(".full-menu").fadeToggle(500)})};function contact_slide(){jQuery('.contact-slide-show').on('click',function(){jQuery('.contact-slide-hide').animate({'right':'0px'})});jQuery('.contact_close').on('click',function(){jQuery('.contact-slide-hide').animate({'right':'-500px'})})};function scroll_top(){jQuery("button.scroltop").on('click',function(){jQuery("html, body").animate({scrollTop:0},1000);return!1});jQuery(window).on("scroll",function(){var scroll=jQuery(window).scrollTop();if(scroll>900){jQuery("button.scroltop").fadeIn(1000)}else{jQuery("button.scroltop").fadeOut(1000)}})}
function input_type_file_form(){jQuery(document).on('change','.btn-file :file',function(){var input=jQuery(this),numFiles=input.get(0).files?input.get(0).files.length:1,label=input.val().replace(/\\/g,'/').replace(/.*\//,'');input.trigger('fileselect',[numFiles,label])});jQuery('.btn-file :file').on('fileselect',function(event,numFiles,label){var input=jQuery(this).parents('.input-group').find(':text'),log=numFiles>10?numFiles+' files selected':label;if(input.length){input.val(log)}else{if(log)alert(log);}})}
function placeholderSupport(){jQuery.support.placeholder=('placeholder' in document.createElement('input'));if(!jQuery.support.placeholder){jQuery("[placeholder]").on('focus',function(){if(jQuery(this).val()===jQuery(this).attr("placeholder"))jQuery(this).val("");}).blur(function(){if(jQuery(this).val()==="")jQuery(this).val(jQuery(this).attr("placeholder"));}).blur();jQuery("[placeholder]").parents("form").on('submit',function(){jQuery(this).find('[placeholder]').each(function(){if(jQuery(this).val()===jQuery(this).attr("placeholder")){jQuery(this).val("")}})})}}
function footer_fixed(){jQuery('.site-footer').css('display','block');jQuery('.site-footer').css('height','auto');var footerHeight=jQuery('.site-footer').outerHeight();jQuery('.footer-fixed > .page-wraper').css('padding-bottom',footerHeight);jQuery('.site-footer').css('height',footerHeight)}
function accordion_active(){$('.acod-head a').on('click',function(){$('.acod-head').removeClass('acc-actives');$(this).parents('.acod-head').addClass('acc-actives');$('.acod-title').removeClass('acc-actives');$(this).parent().addClass('acc-actives');($(this).parents('.acod-head').attr('class'))})}
function mobile_nav(){jQuery(".sub-menu").parent('li').addClass('has-child');jQuery(".mega-menu").parent('li').addClass('has-child');jQuery('.has-child a+.submenu-toogle').on('click',function(ev){jQuery(this).next(jQuery('.sub-menu')).slideToggle('fast',function(){jQuery(this).parent().toggleClass('nav-active')});ev.stopPropagation()})}
function mobile_side_drawer(){jQuery('#mobile-side-drawer').on('click',function(){jQuery('.mobile-sider-drawer-menu').toggleClass('active')})}
function site_search(){jQuery('a[href="#search"]').on('click',function(event){jQuery('#search').addClass('open');jQuery('#search > form > input[type="search"]').focus()});jQuery('#search, #search button.close').on('click keyup',function(event){if(event.target===this||event.target.className==='close'){jQuery(this).removeClass('open')}})}
function testimonial_1_content(){jQuery('.testimonial-1-content').owlCarousel({loop:!0,autoplay:!1,nav:!1,dots:!0,margin:0,navText:['<i class="flaticon-arrows"></i>','<i class="flaticon-point-to"></i>'],responsive:{0:{items:1,},767:{items:2,},1140:{items:3}}})}
function testimonial_2_content(){jQuery('.testimonial-2-content').owlCarousel({loop:!0,autoplay:!0,nav:!0,dots:!1,margin:30,navText:['<i class="flaticon-left"></i>','<i class="flaticon-right"></i>'],responsive:{0:{items:1,},1200:{items:2}}})}
function testimonial_3_content(){jQuery('.testimonial-3-content').owlCarousel({loop:!0,autoplay:!0,nav:!1,dots:!0,margin:30,navText:['<i class="flaticon-left"></i>','<i class="flaticon-right"></i>'],responsive:{0:{items:1,},1200:{items:1}}})}
function testimonial_4_content(){jQuery('.testimonial-4-content').owlCarousel({loop:!0,autoplay:!0,nav:!1,dots:!0,margin:30,navText:['<i class="flaticon-left"></i>','<i class="flaticon-right"></i>'],responsive:{0:{items:1,},767:{items:2,},1200:{items:4,},1366:{items:5}}})}
function project_slider2(){jQuery('.project-slider2').owlCarousel({loop:!0,autoplay:!0,nav:!1,dots:!0,margin:30,navText:['<i class="fa fa-chevron-left"></i>','<i class="fa fa-chevron-right"></i>'],responsive:{0:{items:1,}}})}
function related_posts_carousel(){jQuery('.related-posts-carousel').owlCarousel({loop:!0,autoplay:!0,nav:!1,dots:!0,margin:30,navText:['<i class="fa fa-chevron-left"></i>','<i class="fa fa-chevron-right"></i>'],responsive:{0:{items:1,},800:{items:2,}}})}
function home_client_carousel(){jQuery('.home-client-carousel').owlCarousel({loop:!0,nav:!1,dots:!0,margin:5,autoplay:!0,navText:['<i class="fa fa-angle-left"></i>','<i class="fa fa-angle-right"></i>'],responsive:{0:{items:2,},480:{items:3,},767:{items:4,},1000:{items:5}}})}
function project_slider1(){jQuery('.project-slider1').owlCarousel({loop:!1,nav:!1,dots:!0,margin:30,autoplay:!0,navText:['<i class="fa fa-angle-left"></i>','<i class="fa fa-angle-right"></i>'],responsive:{0:{items:1,},640:{items:2,},767:{items:2,},991:{items:3,},1000:{items:3,},1440:{items:4,},1600:{items:5}}})}
function service_slider_one(){jQuery('.service-slider-one').owlCarousel({loop:!0,nav:!1,dots:!0,margin:1,autoplay:!0,navText:['<i class="fa fa-angle-left"></i>','<i class="fa fa-angle-right"></i>'],responsive:{0:{items:1,},768:{items:2,},1000:{items:3}}})}
function service_slider_two(){jQuery('.service-slider-two').owlCarousel({loop:!0,nav:!1,dots:!0,margin:20,autoplay:!0,navText:['<i class="fa fa-angle-left"></i>','<i class="fa fa-angle-right"></i>'],responsive:{0:{items:1,},768:{items:2,},1000:{items:3}}})}
function counter_section(){jQuery('.counter').counterUp({delay:10,time:3000})}
jQuery('.nav-tabs a').on('click',function(){e.preventDefault();jQuery(this).tab('show')});jQuery('.wt-accordion a').on('click',function(){e.preventDefault();jQuery(this).tab('show')});function home_projects_filter(){var owl=jQuery('.owl-carousel-filter').owlCarousel({loop:!0,autoplay:!0,margin:30,nav:!1,dots:!0,navText:['<i class="fa fa-angle-left"></i>','<i class="fa fa-angle-right"></i>'],responsive:{0:{items:1,},640:{items:1,},767:{items:2,},991:{items:2,},1024:{items:3,}}})
jQuery('.btn-filter-wrap').on('click','.btn-filter',function(e){var filter_data=jQuery(this).data('filter');if(jQuery(this).hasClass('btn-active'))return;jQuery(this).addClass('btn-active').siblings().removeClass('btn-active');owl.owlFilter(filter_data,function(_owl){jQuery(_owl).find('.item').each(owlAnimateFilter)})})}
"use strict";$.fn.owlRemoveItem=function(num){var owl_data=$(this).data('owl.carousel');owl_data._items=$.map(owl_data._items,function(data,index){if(index!=num)return data})
$(this).find('.owl-item').eq(num).remove()}
$.fn.owlFilter=function(data,callback){var owl=this,owl_data=$(owl).data('owl.carousel'),$elemCopy=$('<div>').css('display','none');if(typeof($(owl).data('owl-clone'))=='undefined'){$(owl).find('.owl-item:not(.cloned)').clone().appendTo($elemCopy);$(owl).data('owl-clone',$elemCopy)}else{$elemCopy=$(owl).data('owl-clone')}
owl.trigger('replace.owl.carousel',['<div/>']);switch(data){case '*':$elemCopy.children().each(function(){owl.trigger('add.owl.carousel',[$(this).clone()])})
break;default:$elemCopy.find(data).each(function(){owl.trigger('add.owl.carousel',[$(this).parent().clone()])})
break}
owl.owlRemoveItem(0);owl.trigger('refresh.owl.carousel').trigger('to.owl.carousel',[0]);if(callback)callback.call(this,owl);}
function masonryBox(){if(jQuery().isotope){var $container=jQuery('.masonry-wrap');$container.isotope({itemSelector:'.masonry-item',transitionDuration:'1s',originLeft:!0,stamp:'.stamp'});jQuery('.masonry-filter li').on('click',function(){var selector=jQuery(this).find("a").attr('data-filter');jQuery('.masonry-filter li').removeClass('active');jQuery(this).addClass('active');$container.isotope({filter:selector});return!1})}}
function page_loader(){$('.loading-area').fadeOut(1000)}
function color_fill_header(){var scroll=$(window).scrollTop();if(scroll>=100){$(".is-fixed").addClass("color-fill")}else{$(".is-fixed").removeClass("color-fill")}}
function Bootstrap_Select(){jQuery('.selectpicker').selectpicker()}
jQuery(document).ready(function(){site_search(),video_responsive(),lightbox_popup(),magnific_video(),popup_vertical_center();sticky_header(),sticky_sidebar(),menu_navigation(),contact_slide(),scroll_top(),input_type_file_form(),placeholderSupport(),footer_fixed(),accordion_active(),mobile_nav(),mobile_side_drawer(),project_slider2(),related_posts_carousel(),testimonial_1_content(),testimonial_2_content(),testimonial_3_content(),testimonial_4_content(),home_client_carousel(),project_slider1(),service_slider_one(),service_slider_two(),counter_section(),home_projects_filter()});jQuery(window).on('load',function(){Bootstrap_Select(),masonryBox(),page_loader()});jQuery(window).on('scroll',function(){color_fill_header()});jQuery(window).on('resize',function(){footer_fixed()})})(window.jQuery)